# PyTorch

## What is PyTorch?
Pytorch is an open source Python-based library for implementing and running machine learning algo including wrappers for deep learning. It was primarily developed by the researchers and developers from Facebook AI Research (FAIR) lab.

PyTorch allows execution on CPUs, GPUs and XLA devices such as TPUs. It performes great when using GPUs and XLA devices. It is based on Torch library.

Pytorch has three core components:

1. Tensor library - It extends the concept of the NumPy library with the features to accelerate computation on GPUs and XLA devices. Can easily switch from CPU to GPU.

2. Automatic differentiation engine - Known as autograd, enabeling the automatic computation of gradients for tensor operations, simplifying backpropogation and model optimization. 

3. Deep learning library - It provide the building blocks including pretrained models, loss functions and optimizers for designing and training a deep learning models.

# Section 1: Installation

There are two versions of PyTorch with CPU and with GPU, by default it installs CPU version

With CPU
```
    uv pip install torch torchvision torchaudio
```

With GPU
```
    uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
```


In [6]:
import torch
print(f"PyTorch Version: {torch.__version__}")
print(f"Is GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Using GPU: {torch.cuda.get_device_name()}")

PyTorch Version: 2.10.0+cu126
Is GPU available: True
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


## Setup

Let's import libraries and check Pytorch


In [12]:
# Import core libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

print("Core libraries imported successfully!")


Core libraries imported successfully!


In [75]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Check PyTorch version
print(f"PyTorch Version: {torch.__version__}")
print(f"Is GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Using GPU: {torch.cuda.get_device_name()}")
    
## Set random seeds for reproducibility
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed(42)
    

PyTorch Version: 2.10.0+cu126
Is GPU available: True
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


# Section 2: Tensors Basics

Tensors represents a mathmatical concepts which generalizes vectos and matrices to potentially higher dimensions. These are represneted in ranks or dimensions. For ex: a scaler is a tensor of rank 0, a vector is a tensor of rank 1, a matrix is a tensor of rank 2.

From a computational prespective, tensors are data containers which holds multi-dimentional data, where each dimension represent a feature.As there is no term for higher dimension structure therefore we call them 3D tensor or 4D tensor and so on.

Let's consider a few different ways of creating tensors.

In [ ]:
## Creating PyTorch tensors
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1,2,3])
tensor2d = torch.tensor([[1,2],[3,4]])
tensor3d = torch.tensor([[[1,2], [3,4]],[[5,6], [7,8]]]
)

print(f"Creates a zero-dimension tensor(scaler): {tensor0d}")
print(f"Creates a one-dimension tensor(array): {tensor1d}")
print(f"Creates a two-dimension tensor(matrix): {tensor2d}")
print(f"Creates a three-dimension tensor: {tensor3d}")

Creates a zero-dimension tensor(scaler): 1
Creates a one-dimension tensor(array): tensor([1, 2, 3])
Creates a two-dimension tensor(matrix): tensor([[1, 2],
        [3, 4]])
Creates a three-dimension tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [21]:
## Creating tensor from a list or a NumPy array

import numpy as np
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.tensor(b)

print(f"Tensor: {t_a}, Datatype: {t_a.dtype}, Shape: {t_a.shape}")
print(f"Tensor: {t_b}, Datatype: {t_b.dtype}, Shape: {t_b.shape}")

Tensor: tensor([1, 2, 3]), Datatype: torch.int64, Shape: torch.Size([3])
Tensor: tensor([4, 5, 6], dtype=torch.int32), Datatype: torch.int32, Shape: torch.Size([3])


### Creating tensor with random values


In [24]:
rand_tensor = torch.rand(2,3)
print(f"Tensor: {rand_tensor}")

Tensor: tensor([[0.2335, 0.5702, 0.3966],
        [0.9302, 0.5051, 0.6853]])


### Creating tensor with Zero and Ones

In [73]:
# Zeros and Ones
t_zero = torch.zeros(2,3)
t_ones = torch.ones(2,4)
print(f"Zero: {t_zero}")
print(f"Zero: {t_ones}")

Zero: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Zero: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Check Shape and Datatype

In [25]:
t_ones = torch.ones(2,3)
print(f"Tensor: {t_ones}")
print(f"Datatype: {t_ones.dtype}")
print(f"Shape: {t_ones.shape}")

Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Datatype: torch.float32
Shape: torch.Size([2, 3])


### Manipulating the data type and shape of tensor

It is important to manipulate the tensor data type and it shape to make them compatible for input to a model or an operation.


In [26]:
t_a_float = t_a.to(torch.float32)
print(f"Datatype: {t_a_float.dtype}")

Datatype: torch.float32


Note: If we create a tensor with floats, PyTorch creates tensors with a 32-bit precision by default.

This choice is primarily due to the balance between precision and computational efficiency. A 32-bit floating point number offer sufficient precision for most deep learning tasks while consuming less memory and computation resources than a 64-bit floating point number. Moreover, GPU architecture are mostly optimized for 32-bit computations, and using this data type will significantly speed up our model training and inference.

In [27]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"Datatype: {float_tensor.dtype}")

Datatype: torch.float32


### Transposing a tensor

In [33]:
rand_t = torch.rand(3,4)
transpose_tensor1 = rand_t.T
transpose_tensor2 = torch.transpose(rand_t,0,1)

print(f"Original Tensor: {rand_t}, \nShape: {rand_t.shape}")
print(f"\nTranspose Tensor 1: {transpose_tensor1}, \nShape: {transpose_tensor1.shape}")
print(f"\nTranspose Tensor 2: {transpose_tensor2}, \nShape: {transpose_tensor2.shape}")

Original Tensor: tensor([[0.9185, 0.2806, 0.0730, 0.6812],
        [0.5180, 0.4664, 0.8291, 0.3370],
        [0.1371, 0.0267, 0.7583, 0.6563]]), 
Shape: torch.Size([3, 4])

Transpose Tensor 1: tensor([[0.9185, 0.5180, 0.1371],
        [0.2806, 0.4664, 0.0267],
        [0.0730, 0.8291, 0.7583],
        [0.6812, 0.3370, 0.6563]]), 
Shape: torch.Size([4, 3])

Transpose Tensor 2: tensor([[0.9185, 0.5180, 0.1371],
        [0.2806, 0.4664, 0.0267],
        [0.0730, 0.8291, 0.7583],
        [0.6812, 0.3370, 0.6563]]), 
Shape: torch.Size([4, 3])


### Reshaping and Indexing

We can use reshape() or view() method for reshaping the tensor.

In [111]:
tensor2d = torch.arange(12)
print(f"Original: {tensor2d}, \nShape: {tensor2d.shape}")
print(f"\nReshaped: {tensor2d.reshape(2,6)}, \nShape: {tensor2d.reshape(2,6).shape}")
print(f"\nReshaped: {tensor2d.view(3,4)}, \nShape: {tensor2d.view(3,4).shape}")

# Indexing
print("\nFirst row : ", tensor2d.reshape(2,6)[0])
print("\nFirst column : ", tensor2d.view(3,4)[:,0])
print("\nElement[1,2] : ", tensor2d.view(3,4)[1,2])

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), 
Shape: torch.Size([12])

Reshaped: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), 
Shape: torch.Size([2, 6])

Reshaped: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), 
Shape: torch.Size([3, 4])

First row :  tensor([0, 1, 2, 3, 4, 5])

First column :  tensor([0, 4, 8])

Element[1,2] :  tensor(6)


### Removing unnecessary dimensions

In [70]:
tensor_zero = torch.zeros(1,2,1,4,1,3)
print(f"Original Shape: {tensor_zero.shape}")
t_sqz = torch.squeeze(tensor_zero)
print(f"Squeezed Shape: {t_sqz.shape}")

Original Shape: torch.Size([1, 2, 1, 4, 1, 3])
Squeezed Shape: torch.Size([2, 4, 3])


### Mathematical Operations 

In [105]:
# Tensor Operations
a = torch.rand(3,2)
b = torch.normal(mean=0, std=1, size=(3,2))

print("a: ", a)
print("b: ", b)
print("\nMathematical Operations")
# Addition
print("a + b = ", a + b)
# Subtraction
print("a - b = ", a - b)
# Multiplication: element wise
print("a * b = ", a * b)
# Multiplication: dotproduct or matrix product
print("a @ b = ", a @ b.T)
print("Matrix Product = ", torch.matmul(a,b.T))
# tensor sum
print("a.sum() = ", a.sum())
# tensor mean
print("a.mean() = ", a.mean())
# Tensor standard deviation
print("b.std() = ", b.std())
## max value
print("a.max() = ", a.max())


a:  tensor([[0.3289, 0.1054],
        [0.9192, 0.4008],
        [0.9302, 0.6558]])
b:  tensor([[-1.6270, -1.3951],
        [-0.2387, -0.5050],
        [-2.4752, -0.9316]])

Mathematical Operations
a + b =  tensor([[-1.2982, -1.2898],
        [ 0.6805, -0.1042],
        [-1.5450, -0.2758]])
a - b =  tensor([[1.9559, 1.5005],
        [1.1580, 0.9058],
        [3.4054, 1.5874]])
a * b =  tensor([[-0.5350, -0.1470],
        [-0.2194, -0.2024],
        [-2.3024, -0.6109]])
a @ b =  tensor([[-0.6820, -0.1317, -0.9121],
        [-2.0547, -0.4218, -2.6486],
        [-2.4284, -0.5532, -2.9133]])
Matrix Product =  tensor([[-0.6820, -0.1317, -0.9121],
        [-2.0547, -0.4218, -2.6486],
        [-2.4284, -0.5532, -2.9133]])
a.sum() =  tensor(3.3402)
a.mean() =  tensor(0.5567)
b.std() =  tensor(0.8155)
a.max() =  tensor(0.9302)


### Split, Stack and Concatenate

torch.chunk() - We can split a tensor into a list of equal size tensor with desired dimension specified by dim argument.


In [116]:
## Providing the number of splits
t = torch.rand(6)
print(f"Input Tensor : {t}")
t_split = t.chunk(3)
print(f"Splitted Tensor : {t_split}")
print("\nThe tensor was divided into 3 equal size tensor. If the tensor size is not divisible equally then last chunk will be smaller")

Input Tensor : tensor([0.6115, 0.2234, 0.2469, 0.4761, 0.7792, 0.3722])
Splitted Tensor : (tensor([0.6115, 0.2234]), tensor([0.2469, 0.4761]), tensor([0.7792, 0.3722]))

The tensor was divided into 3 equal size tensor. If the tensor size is not divisible equally then last chunk will be smaller


In [119]:
## Providing the size of different splits
t = torch.rand(7)
print(f"Input Tensor : {t}")
t_split = t.split([3,4])
t_split_2 = t.split(3)
print(f"\nSplitted Tensor : {t_split}")
print(f"\nSplitted Tensor : {t_split_2}")

Input Tensor : tensor([0.3676, 0.5535, 0.4117, 0.3510, 0.8196, 0.9297, 0.4505])

Splitted Tensor : (tensor([0.3676, 0.5535, 0.4117]), tensor([0.3510, 0.8196, 0.9297, 0.4505]))

Splitted Tensor : (tensor([0.3676, 0.5535, 0.4117]), tensor([0.3510, 0.8196, 0.9297]), tensor([0.4505]))


We can concatenate tensor together in the given dimension. All tensor must have the same shape except in the concatenating direction or should be 1D.

In [124]:
A = torch.ones(2,3)
B = torch.zeros(2,4)
print(torch.cat([A,B], axis=1))

tensor([[1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0.]])


Concatenating tensors of same size into a new dimension.

In [130]:
A = torch.ones(2)
B = torch.zeros(2)
print(torch.stack([A,B], axis=1))
print("\n",torch.stack([A,B], axis=0))

tensor([[1., 0.],
        [1., 0.]])

 tensor([[1., 1.],
        [0., 0.]])


### GPU Tensors

One of PyTorch's strengths is easy GPU acceleration:

In [134]:
# Create tensor on cpu
device = torch.device(
    'cuda' if torch.cuda.is_available() else
    'mps' if torch.mps.is_available() else 'cpu'
)
print(f"Using device: {device}")

x_cpu = torch.rand(2,3)
print(f"CPU tensor device: {x_cpu.device}")

# Move to GPU
x_gpu = x_cpu.to(device)
print(f"GPU tensor device: {x_gpu.device}")

# Or create directly on device
y = torch.ones(3, 3, device=device)
print(f"Direct creation device: {y.device}")

Using device: cuda
CPU tensor device: cpu
GPU tensor device: cuda:0
Direct creation device: cuda:0


### Autograd - Automatic Differentiation

PyTorch's autograd provides functions to automatically compute gradients in dynamic computational graph.

A computational graph is a direct graph that allow us to express and visualise mathematical expressions. In deep learning, it lays outs the sequence of calculations needed to compute the output of a neural network which we will use to compute gradietns for backpropogation.

Let's look at an example to understand the concept of computational graph. We will be implementing the forward propogation of a simple logistic regression classifier, which can be seen as a single layer neural-network which returns a score between 0 and 1, which is then compared to the true class label (0 ot 1) when computing the loss.

In [137]:
#True label
y = torch.tensor([1.0])
# Input Feature
x1 = torch.tensor([1.1])
# Weight Parameter
w1 = torch.tensor([2.2])
# Bias 
b = torch.tensor([0.0])
# Net Input
z = x1 * w1 + b
# activation and output
a = torch.sigmoid(z)
# calculate loss
loss = F.binary_cross_entropy(a,y)
print(loss)

tensor(0.0852)


When we carry out computations in PyTorch, autograd engine builds a computation graph internally if any of its terminal node has the `required_grad` attribute as True by traking every operation performed on tensors. It is useful when we have to calculate gradients which are required while training neural network by calling `grad` function.



In [139]:
from torch.autograd import grad

#True label
y = torch.tensor([1.0])
# Input Feature
x1 = torch.tensor([1.1])
# Weight Parameter
w1 = torch.tensor([2.2], requires_grad=True)
# Bias 
b = torch.tensor([0.0], requires_grad=True)
# Net Input
z = x1 * w1 + b
# activation and output
a = torch.sigmoid(z)
# calculate loss
loss = F.binary_cross_entropy(a,y)


grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


Here we have calculated grad function manually which is useful for experimentation, debugging and demonstration concepts. But PyTorch provides .backward(), a high-level tool to automate this process. We can call .backward() on loss and it will compute the gradients of all the leaf nodes in the graph which will be stored via the tensor.grad attribute.

In [140]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## Section 3: Data Handling

### Building Input Pipelines

When we are training a deep neural network, we usually train the model incrementally using an iterative optimization algo such as stochastic gradient descent. When the dataset is to large to fit into the compute memory we load the data from the main storage in chunks that is batch by batch.

Then we need to construct a data-processing pipeline to apply certain transformation and preprocessing techniques to our data, such as normalization, scaling, encoding or adding noise to augment the training procedures and to prevent overfitting.

PyTorch provides `Dataset` and `DataLoader` for efficient data handling.

### Creating Dataloader from existing tensor

If our data already exists as a tensor object, a python list or a NumPy array, we can easily create a dataset loader using `torch.utils.data.DataLoader()` class.

In [152]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)

for i in data_loader:
    print(i)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


If we want to create batches of desired batch size we can do that with `batch_size` argument. The optional `drop_last` argument is useful when the elements in the tensor is not divisible by the desired batch size.

In [159]:
t_new = torch.arange(7, dtype=torch.float32)
data_loader = DataLoader(t_new, batch_size=3, drop_last=False)
print("With batch_size = 3 and drop_last=False: ")
for i in data_loader:
    print(i)
    
data_loader = DataLoader(t_new, batch_size=3, drop_last=True)
print("\nWith batch_size = 3 and drop_last=True: ")
for i in data_loader:
    print(i)

With batch_size = 3 and drop_last=False: 
tensor([0., 1., 2.])
tensor([3., 4., 5.])
tensor([6.])

With batch_size = 3 and drop_last=True: 
tensor([0., 1., 2.])
tensor([3., 4., 5.])


### Combining two tensor into a joint dataset
Many a times we have to combine the data available in two tensors. For ex, we could have features in one tensor and lables in another. In such case, we would have to combine the tensors to build a common dataset which will allow us to retrieve the elements of these tensors in tuples.

To create a joint dataset from two tensors we need to create a `Dataset` class. A custom `Dataset` class must contain 

In [ ]:
## We have two tensors x and y which holds features (size 3) and lables respectively.
from torch.utils.data import Dataset

x = torch.rand([4,3], dtype=torch.float32)
y = torch.arange(4)

class JointDataset(Dataset):
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

## creating an object of Jointdataset
jd_obj = JointDataset(x,y)
jd_obj.__len__()
for item in range( jd_obj.__len__()):
    print(jd_obj.__getitem__(item))
        


We can directly create a joint dataset by calling `TensorDataset()` directly, if one of the tensor is a labeled dataset.

In [168]:
from torch.utils.data import TensorDataset

joint_dataset = TensorDataset(x,y)

for i in joint_dataset:
    print(i)

(tensor([0.3413, 0.0248, 0.9103]), tensor(0))
(tensor([0.9192, 0.4216, 0.4431]), tensor(1))
(tensor([0.2959, 0.0485, 0.0134]), tensor(2))
(tensor([0.6858, 0.2255, 0.1786]), tensor(3))


### Shuffle, Batch and Repeat

While training our NN model it is important to feed training data as randomly shuffled batches. Therefore we will shuffle and retiterate over datasets. The rows will be shuffled without loosing the one-to-one correspondense between the entire in x and y.

In [178]:
data_loader = DataLoader(dataset= joint_dataset, batch_size=2, shuffle=True)

for i,batch in enumerate(data_loader, 1):
    print(f"Batch {i}: \nx: {batch[0]} \ny: {batch[1]}\n")

Batch 1: 
x: tensor([[0.2959, 0.0485, 0.0134],
        [0.6858, 0.2255, 0.1786]]) 
y: tensor([2, 3])

Batch 2: 
x: tensor([[0.9192, 0.4216, 0.4431],
        [0.3413, 0.0248, 0.9103]]) 
y: tensor([1, 0])



When we train our model for multiple epochs, we need to shuffle and iterate over the dataset by the desired number of epochs. 